package com.example.Prime_Source.enums;

public enum ResultStatus {
    PENDING,       
	SCHEDULED,
    INTERVIEWED,
    PLACED,
    REJECTED,
    
    SUBMITTED_BY_CLIENT,
    CLIENT_SHORTLIST,
    FIRST_INTERVIEW_SCHEDULED,
    FIRST_INTERVIEW_FEEDBACK_PENDING,
    FIRST_INTERVIEW_REJECT,
    
    
    SECOND_INTERVIEW_SCHEDULED,
    SECOND_INTERVIEW_FEEDBACK_PENDING,
    SECOND_INTERVIEW_REJECT,
    
    
    THIRD_INTERVIEW_SCHEDULED,
    THIRD_INTERVIEW_FEEDBACK_PENDING,
    THIRD_INTERVIEW_REJECT,
    
    INTERNEL_REJECT,
    CLIENT_REJECT,
    FINAL_SELECT,
    JOINED,
    BACKEDOUT
    
}
	